# Matrix Operations with Numpy

# Base Python makes it tough to deal with matrices. Numpy is designed to deal with matrices!

In [1]:
import numpy as np

Looking at a sample matrix.

# A sample matrix and accessing elements

In [2]:
matrix = np.array([[-2, 3, 1],
                   [0,  9, 2],
                   [3, -1, -1]])
print(matrix)
print(matrix.shape)

[[-2  3  1]
 [ 0  9  2]
 [ 3 -1 -1]]
(3, 3)


### Each element of the matrix is specificed by a row and column (zero-indexed). We can access each element with **slicing**, which looks like this.

In [3]:
row    = 1
column = 0

print(matrix[row,column])

0


### I can get entire rows or entire columns with the colon operator, which looks like this:

In [4]:
print(matrix[:,column])

[-2  0  3]


In [5]:
print(matrix[0:2,column]) # note that the slicing is NOT inclusive!

[-2  0]


# Operations

### Matrix Multiplication (np.matmul(), or the @ operator)

In [6]:
x = np.array([[1,0,0],
              [0,0,0],
              [0,0,0]])

y = np.random.rand(3,3)
print(y)

[[0.14249597 0.07878605 0.94982515]
 [0.22226144 0.37718654 0.49596761]
 [0.81734986 0.29249554 0.08123596]]


In [7]:
print(y @ x)
print(' ')
print(np.matmul(y,x))

[[0.14249597 0.         0.        ]
 [0.22226144 0.         0.        ]
 [0.81734986 0.         0.        ]]
 
[[0.14249597 0.         0.        ]
 [0.22226144 0.         0.        ]
 [0.81734986 0.         0.        ]]


### Inverses

In [8]:
array = np.random.rand(3,3)
array_inverse = np.linalg.inv(array)

In [9]:
print(array)
print('')
print(array_inverse)
print('')
print(array @ array_inverse)

[[0.18845774 0.47489393 0.06798435]
 [0.71992277 0.70571139 0.70494174]
 [0.03339593 0.17457315 0.08358133]]

[[  2.84423372   1.23499578 -12.7296779 ]
 [  1.62585364  -0.59837357   3.72434718]
 [ -4.5323065    0.75634259   9.27178841]]

[[ 1.00000000e+00  5.82187853e-18  5.67395671e-17]
 [ 2.89179408e-16  1.00000000e+00 -9.19840824e-16]
 [ 1.25907567e-16  1.76515617e-17  1.00000000e+00]]


### Tranposing

In [10]:
x = np.array([[1,2,3],
             [4,5,6]])

print(x)
print('')
print(x.shape)
print('')
x_transpose = x.T # or np.tranpose()
print(x_transpose)
print('')
print(x_transpose.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)

[[1 4]
 [2 5]
 [3 6]]

(3, 2)


In [11]:
x @ x_transpose

array([[14, 32],
       [32, 77]])

In [12]:
x @ x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Other useful functions that I use often:

* np.zeros()
* np.ones()
* np.hstack() -- stacks arrays columnwise
* np.vstack() -- stack arrays rowwise
* np.save(), np.load() -- saves and loads .npy files 
* np.genfromtxt(), np.loadtxt(), np.savetxt()
* np.random.uniform()
* np.random.normal()
* 